#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
IFS=" "
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid

if ! [[ -f $(pwd)/AUTHORS ]]; then
	echo "No existe el archivo AUTHORS"
	exit 1
else
	echo "El archivo AUTHORS existe"
fi

if ! [[ -f $(pwd)/COPYING ]]; then
	echo "No existe el archivo COPYING"
	exit 1
else
	echo "El archivo COPYING existe"
fi

if ! [[ -d $(pwd)/debian ]]; then
	echo "No existe el directorio debian"
	exit 1
else
	echo "El directorio debian existe"
fi

if ! [[ -f $(pwd)/debian/changelog ]]; then
	echo "No existe el archivo debian/changelog"
	exit 1
else
	echo "El archivo debian/changelog existe"
fi

if ! [[ -f $(pwd)/debian/compat ]]; then
	echo "No existe el archivo debian/compat"
	exit 1
else
	echo "El archivo debian/compat existe"
fi

if ! [[ -f $(pwd)/debian/conffiles ]]; then
	echo "No existe el archivo debian/conffiles"
	exit 1
else
	echo "El archivo debian/conffiles existe"
fi

if ! [[ -f $(pwd)/debian/control ]]; then
	echo "No existe el archivo debian/control"
	exit 1
else
	echo "El archivo debian/control existe"
fi

if ! [[ -f $(pwd)/debian/copyright ]]; then
	echo "No existe el archivo debian/copyright"
	exit 1
else
	echo "El archivo debian/copyright existe"
fi

if ! [[ -f $(pwd)/debian/install ]]; then
	echo "No existe el archivo debian/install"
	exit 1
else
	echo "El archivo debian/install existe"
fi

if ! [[ -f $(pwd)/debian/md5sums ]]; then
	echo "No existe el archivo debian/md5sums"
	exit 1
else
	echo "El archivo debian/md5sums existe"
fi

if ! [[ -f $(pwd)/debian/postinst ]]; then
	echo "No existe el archivo debian/postinst"
	exit 1
else
	echo "El archivo debian/postinst existe"
fi

if ! [[ -f $(pwd)/debian/postrm ]]; then
	echo "No existe el archivo debian/postrm"
	exit 1
else
	echo "El archivo debian/postrm existe"
fi

if ! [[ -f $(pwd)/debian/preinst ]]; then
	echo "No existe el archivo debian/preinst"
	exit 1
else
	echo "El archivo debian/preinst existe"
fi

if ! [[ -f $(pwd)/debian/prerm ]]; then
	echo "No existe el archivo debian/prerm"
	exit 1
else
	echo "El archivo debian/prerm existe"
fi

if ! [[ -f $(pwd)/debian/rules ]]; then
	echo "No existe el archivo debian/rules"
	exit 1
else
	echo "El archivo debian/rules existe"
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Source") ]]; then
	echo "El campo Source en el archivo control existe"
else
	echo "El campo Source en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Section") ]]; then
	echo "El campo Section en el archivo control existe"
else
	echo "El campo Section en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Priority") ]]; then
	echo "El campo Priority en el archivo control existe"
else
	echo "El campo Priority en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Maintainer") ]]; then
	echo "El campo Maintainer en el archivo control existe"
else
	echo "El campo Maintainer en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Build-Depends") ]]; then
	echo "El campo Build-Depends en el archivo control existe"
else
	echo "El campo Build-Depends en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Build-Depends" | grep "debhelper") ]]; then
	echo "El campo Build-Depends del archivo control contiene el parametro debhelper"
else
	echo "El campo Build-Depends del archivo control NO contiene el parametro debhelper"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Build-Depends" | grep "cdbs") ]]; then
	echo "El campo Build-Depends del archivo control contiene el parametro cdbs"
else
	echo "El campo Build-Depends del archivo control NO contiene el parametro cdbs"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Standards-Version") ]]; then
	echo "El campo Standards-Version en el archivo control existe"
else
	echo "El campo Standards-Version en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Homepage") ]]; then
	echo "El campo Homepage en el archivo control existe"
else
	echo "El campo Homepage en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Vcs-Bzr") ]]; then
	echo "El campo Vcs-Bzr en el archivo control existe"
else
	echo "El campo Vcs-Bzr en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Package") ]]; then
	echo "El campo Package en el archivo control existe"
else
	echo "El campo Package en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Architecture") ]]; then
	echo "El campo Architecture en el archivo control existe"
else
	echo "El campo Architecture en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Depends") ]]; then
	echo "El campo Depends en el archivo control existe"
else
	echo "El campo Depends en el archivo control NO existe"
	exit 1
fi

if ! [[ -z $(cat $(pwd)/debian/control | grep "Description") ]]; then
	echo "El campo Description en el archivo control existe"
else
	echo "El campo Description en el archivo control NO existe"
	exit 1
fi




if ! [[ -d $(pwd)/debian/source ]]; then
	echo "No existe el directorio debian/source"
	exit 1
else
	echo "El directorio debian/source existe"
fi

if ! [[ -f $(pwd)/debian/source/format ]]; then
	echo "No existe el archivo debian/source/format"
	exit 1
else
	echo "El archivo debian/source/format existe"
fi

if ! [[ -z $(cat $(pwd)/debian/source/format | grep "3.0 (quilt)") ]]; then
	echo "El archivo /debian/source/format contiene 3.0 (quilt)"
else
	echo "El archivo /debian/source/format NO contiene 3.0 (quilt)"
	exit 1
fi



* Verificar que el campo **Architecture** del archivo **control** contenga el valor: **all**
* Verificar que la lista de dependencias finalice con las siguientes variables: **${misc:Depends}**, **${shlibs:Depends}**, **${perl:Depends}**
* Verificar que los archivos: **changelog**, **control**, **copyright**, **COPYING** hagan referencia al nombre del paquete que corresponden
* Verificar que los archivos: **postinst**, **postrm**, **preinst**, **prerm** contengan las funciones correspondientes a cada fase de dpkg.
* Verificar que el archivo: **compat** tenga el valor **9**
* Verificar que los archivos **install**, **md5sums** contengan la lista de todos los archivos a instalar
* Verificar que el archivo: **conffiles** contenga la lista de todos los archivos de configuración dentro del paquete.
* Verificar que el archivo: **rules** tenga el mismo contenido que el paquete de ejemplo publicado en [git](https://github.com/sinfallas/package-examples).
* Verificar que los archivos a instalar no estén dentro de ningún directorio




echo " El paquete supero todos las pruebas exitosamente."
rm -f /run/$(basename $0).pid
exit 0
